### ISSUE TITLE
Eliminate local database and switch to Firebase

### ISSUE THREAD

**Issue by pr4h6n** [qwertynerd97/bball-collector#1]
Remove local MySQL database and retrieve data from Firebase database instead. Stored my android studio project on trades_messages branch.

**Comment by pr4h6n** [comment]
Removed the classes involved but the trading logic still uses the non-existent local database. Needs to be refactored to use Firebase instead. Waiting for Firebase database to match format needed to conduct trades (Firebase needs to store cards for each user).

**Comment by qwertynerd97** [comment]
Firebase database can now store cards and trades.  (None currently exist, but encapsulating code will push them as they are created)  Please update trading logic to match database interactions as seen in UserSearchActivity

**Comment by pr4h6n** [comment]
Began eliminating code that depended on a local MySQL database and replaced with code accessing Firebase directly

**Comment by pr4h6n** [comment]
Eliminated code that depended on local MySQL database and replaced with code for accessing Firebase directly (for trading service)
