### ISSUE TITLE
Collection Grid View?

### ISSUE THREAD

**Issue by eezstreet** [qwertynerd97/bball-collector#18]
What precisely is the Collection View supposed to do when you click on a grid item? Are you meant to select a card in the grid view and then hit a View/Edit/Delete button on it? Or does clicking on the item in the grid view bring up the View Card Activity, and from there you are supposed to click on an Edit or Delete button on the card?

**Comment by pr4h6n** [comment]
When you select a card in the grid view it displays the card details. There should be an edit button in the top right and a delete button on the bottom of the screen.

**Comment by eezstreet** [comment]
Thank you. That answers my question perfectly.
