### ISSUE TITLE
Handoff.currentUser is sometimes null.

### ISSUE THREAD

**Issue by eezstreet** [qwertynerd97/bball-collector#28]
I registered an account with my username and a password a while ago. Now, whenever I log in with that username, Handoff.currentUser winds up being null.

**Comment by pr4h6n** [comment]
Where is it null?

**Comment by eezstreet** [comment]
Any time after login. The collection and wishlist don't trigger errors though. I encountered a crash in the Add Card action as well as a few other activities.

**Comment by HanielDiaz** [comment]
Is it possible that you might be putting the log in information wrong? I made an account and can log in and don't get any run-time errors or abnormalities.

**Comment by eezstreet** [comment]
Pretty sure it's right, otherwise I would've gotten an authentication error. I'll try making a dummy account and see if it's just an anomaly with the account I'm using.

**Comment by eezstreet** [comment]
This looks like just a weird fluke with Firebase. When I created a new account, everything appeared normally.
