### ISSUE TITLE
Need user interface for Collection/Wishlist

### ISSUE THREAD

**Issue by qwertynerd97** [qwertynerd97/bball-collector#4]
- [x] Acess Nav Drawer
- [x] View cards in list (See SearchUserActivity for format)
- [ ] Sort cards by criteria in project requirements (Use query.sortBy('key'))
- [ ] Search for cards
- [x] Add new card
- [x] Edit/Delete card
- [x] Go to card detail

**Comment by pr4h6n** [comment]
Whoever ends up writing the code for the card collection, make sure to disable edit/delete privileges for cards with lockstatus = true. This prevents users from modifying or deleting cards that are part of a pending trade

**Comment by eezstreet** [comment]
@pr4h6n are you working on this? I noticed that you made a `user_collection` branch.

**Comment by pr4h6n** [comment]
I started working on it but anyone else is free to work on it as well

**Comment by eezstreet** [comment]
I'll give it a go, then, working from the current `user_collection` branch.

**Comment by pr4h6n** [comment]
CardDetailActivity can now display the selected card's details

**Comment by eezstreet** [comment]
The Nav Drawer works. Added a "Add New Card" button and associated fullscreen activity.
