### ISSUE TITLE
Need User Interface for Wishlist

### ISSUE THREAD

**Issue by qwertynerd97** [qwertynerd97/bball-collector#5]
- [ ] Acess Nav Drawer
- [ ] View cards in list (See SearchUserActivity for format)
- [ ] Sort cards by criteria in project requirements (Use query.sortBy('key'))
- [ ] Add new card
- [ ] Go to card detail

**Comment by eezstreet** [comment]
These are now handled in the same activity as Collection. So there is no need to recode these specific to the wishlist.
