### ISSUE TITLE
Need User interface for Trades

### ISSUE THREAD

**Issue by qwertynerd97** [qwertynerd97/bball-collector#6]
- [x] Acess Nav Drawer
- [x] View trades in list (See SearchUserActivity for format)
- [x] Add new trade
- [x] Go to trade detail

**Comment by pr4h6n** [comment]
Began working on trades interface. User can view trades in list. Started working on viewing trade details and adding a new trade

**Comment by pr4h6n** [comment]
User can now view trade in detail and respond (accept or reject trade). User can create new trade
